### ISSUE TITLE
ffmpeg_plugin is not compatible with n4.3

### ISSUE THREAD

**Issue by jbeich** [OpenVisualCloud/SVT-VP9#124]
Only `master` applied against `n4.3` before but now regressed by #119. From [error log](https://github.com/OpenVisualCloud/SVT-VP9/files/4906600/ffmpeg-4.3_4.1.log):
```c
libavcodec/libsvt_vp9.c:32:10: fatal error: 'encode.h' file not found
#include "encode.h"
         ^~~~~~~~~~
1 error generated.
```

**Comment by jbeich** [comment]
Downstream FreeBSD provides a convenient way to build **system** ffmpeg with SVT encoders but only **one** version of ffmpeg is supported, usually the latest. SVT-AV1 is not affected because it has `LIBAVCODEC_VERSION_INT` conditionals instead of multiple patches.

**Comment by 1480c1** [comment]
@guojiansheng0925 can you check to see if you can do something similar to https://github.com/OpenVisualCloud/SVT-AV1/blob/master/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch#L120 for the patches here?

**Comment by guojiansheng0925** [comment]
Hi @1480c1, the LIBAVCODEC_VERSION_INT checks were removed by @jamrial in #119 because it is unnecessary for master branch. May be we should make a new patch for n4.3 branch only?
Which solution do you think is better? Revert or add a new patch?

**Comment by 1480c1** [comment]
I think it may be better to revert in this case since we aren't planning to immediately upstream the svt-vp9 patches, so it would be better if we kept the contents of libsvt_vp9.c as close as possible between all of the patches to reduce maintenance burden

**Comment by VVD** [comment]
It work with ffmpeg 4.3.1 now, thanks!
Can you create new tag v0.2.2?

**Comment by tianjunwork** [comment]
@VVD , v0.2.2 tag is added.

**Comment by VVD** [comment]
Thanks!
