### ISSUE TITLE
Build error MacOS 10.15.2

### ISSUE THREAD

**Issue by FreddyX078** [OpenVisualCloud/SVT-VP9#76]
After building SVT-AV1 and SVT-HEVC, now trying to build on MacOS Catalina 10.15.2 but this one fails with the following error:

$ cmake -DCMAKE_INSTALL_PREFIX=/usr/local/bin -DBUILD_SHARED_LIBS=0 ../
-- Found YASM: /usr/local/bin/bin/yasm
-- CMAKE_BUILD_TYPE = Release
-- CMAKE_C_COMPILER = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- CMAKE_ASM_NASM_COMPILER = /usr/local/bin/bin/yasm
-- CMAKE_AR = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar
-- CMAKE_RANLIB = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib
-- CMAKE_INSTALL_PREFIX = /usr/local/bin
-- Configuring done
-- Generating done
-- Build files have been written to: svt-vp9/SVT-VP9/Build
$ make
[ 30%] Built target libVPX
[ 39%] Built target VP9_ASM_AVX2
[ 43%] Built target VP9_C_DEFAULT
[ 54%] Built target VP9_ASM_SSE2
[ 58%] Built target VP9_ASM_SSSE3
[ 59%] Built target VP9_ASM_SSE4_1
[ 60%] Building C object Source/Lib/Codec/CMakeFiles/SvtVp9Enc.dir/EbEncHandle.c.o
svt-vp9/SVT-VP9/Source/Lib/Codec/EbEncHandle.c:390:39: error: use of undeclared identifier 'eb_vp9_lp_group'; did you mean
      'eb_vp9_num_groups'?
    memset(eb_vp9_lp_group, 0, sizeof(eb_vp9_lp_group));
                                      ^~~~~~~~~~~~~~~
                                      eb_vp9_num_groups
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/secure/_string.h:77:33: note: 
      expanded from macro 'memset'
                __builtin___memset_chk (dest, __VA_ARGS__, __darwin_obsz0 (dest))
                                              ^
svt-vp9/SVT-VP9/Source/Lib/Codec/EbEncHandle.c:127:34: note: 'eb_vp9_num_groups' declared here
uint8_t                          eb_vp9_num_groups = 0;
                                 ^
svt-vp9/SVT-VP9/Source/Lib/Codec/EbEncHandle.c:390:12: error: use of undeclared identifier 'eb_vp9_lp_group'; did you mean
      'eb_vp9_num_groups'?
    memset(eb_vp9_lp_group, 0, sizeof(eb_vp9_lp_group));
           ^~~~~~~~~~~~~~~
           eb_vp9_num_groups
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/secure/_string.h:77:62: note: 
      expanded from macro 'memset'
                __builtin___memset_chk (dest, __VA_ARGS__, __darwin_obsz0 (dest))
                                                                           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/secure/_common.h:38:55: note: 
      expanded from macro '__darwin_obsz0'
#define __darwin_obsz0(object) __builtin_object_size (object, 0)
                                                      ^
svt-vp9/SVT-VP9/Source/Lib/Codec/EbEncHandle.c:127:34: note: 'eb_vp9_num_groups' declared here
uint8_t                          eb_vp9_num_groups = 0;
                                 ^
svt-vp9/SVT-VP9/Source/Lib/Codec/EbEncHandle.c:390:12: error: use of undeclared identifier 'eb_vp9_lp_group'; did you mean
      'eb_vp9_num_groups'?
    memset(eb_vp9_lp_group, 0, sizeof(eb_vp9_lp_group));
           ^~~~~~~~~~~~~~~
           eb_vp9_num_groups
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/secure/_string.h:77:27: note: 
      expanded from macro 'memset'
                __builtin___memset_chk (dest, __VA_ARGS__, __darwin_obsz0 (dest))
                                        ^
svt-vp9/SVT-VP9/Source/Lib/Codec/EbEncHandle.c:127:34: note: 'eb_vp9_num_groups' declared here
uint8_t                          eb_vp9_num_groups = 0;
                                 ^
svt-vp9/SVT-VP9/Source/Lib/Codec/EbEncHandle.c:412:13: error: use of undeclared identifier 'eb_vp9_lp_group'; did you mean
      'eb_vp9_num_groups'?
            eb_vp9_lp_group[socket_id].group[eb_vp9_lp_group[socket_id].num++] = processor_id;
            ^~~~~~~~~~~~~~~
            eb_vp9_num_groups
svt-vp9/SVT-VP9/Source/Lib/Codec/EbEncHandle.c:127:34: note: 'eb_vp9_num_groups' declared here
uint8_t                          eb_vp9_num_groups = 0;
                                 ^
svt-vp9/SVT-VP9/Source/Lib/Codec/EbEncHandle.c:412:28: error: subscripted value is not an array, pointer, or vector
            eb_vp9_lp_group[socket_id].group[eb_vp9_lp_group[socket_id].num++] = processor_id;
            ~~~~~~~~~~~~~~~^~~~~~~~~~
svt-vp9/SVT-VP9/Source/Lib/Codec/EbEncHandle.c:412:46: error: use of undeclared identifier 'eb_vp9_lp_group'
            eb_vp9_lp_group[socket_id].group[eb_vp9_lp_group[socket_id].num++] = processor_id;
                                             ^
svt-vp9/SVT-VP9/Source/Lib/Codec/EbEncHandle.c:602:14: warning: unused variable 'num_logical_processors' [-Wunused-variable]
    uint32_t num_logical_processors = get_num_cores();
             ^
svt-vp9/SVT-VP9/Source/Lib/Codec/EbEncHandle.c:600:69: warning: unused parameter 'config_ptr' [-Wunused-parameter]
void eb_set_thread_management_parameters( EbSvtVp9EncConfiguration *config_ptr){
                                                                    ^
svt-vp9/SVT-VP9/Source/Lib/Codec/EbEncHandle.c:2981:17: warning: unused parameter 'msg' [-Wunused-parameter]
    const char *msg,
                ^
svt-vp9/SVT-VP9/Source/Lib/Codec/EbEncHandle.c:2983:11: warning: unused parameter 'error' [-Wunused-parameter]
    Errno error)
          ^
4 warnings and 6 errors generated.
make[2]: *** [Source/Lib/Codec/CMakeFiles/SvtVp9Enc.dir/EbEncHandle.c.o] Error 1
make[1]: *** [Source/Lib/Codec/CMakeFiles/SvtVp9Enc.dir/all] Error 2
make: *** [all] Error 2

Don't find anything on the net, so I'm asking here and hoping for some help.

**Comment by 1480c1** [comment]
I do not think macOS is yet supported with SVT-VP9

**Comment by 1480c1** [comment]
Also, I recommend to surround your log with triple backticks ` ``` ` to prevent formatting
```none
something like this
```

**Comment by FreddyX078** [comment]
Sorry, my first post here and wasn't sure which one to use.

Sad to hear MacOS isn't supported yet. But it clarifies why it won't build. Hopefully it will be supported in the future.

**Comment by tianjunwork** [comment]
Hi @FreddyX078, as @1480c1 said, MacOS support is not yet added for SVT-VP9.
We do welcome the contribution from the community.
