### PR TITLE
FFmpeg: make master patch compatible with n4.3 branch

### LINKED ISSUE #124: ffmpeg_plugin is not compatible with n4.3
Only `master` applied against `n4.3` before but now regressed by #119. From [error log](https://github.com/OpenVisualCloud/SVT-VP9/files/4906600/ffmpeg-4.3_4.1.log):
```c
libavcodec/libsvt_vp9.c:32:10: fatal error: 'encode.h' file not found
#include "encode.h"
         ^~~~~~~~~~
1 error generated.
```

### PR DESCRIPTION
**Pull request by guojiansheng0925**
fixes #124 
Signed-off-by: Guo Jiansheng <jiansheng.guo@intel.com>

### CODE REVIEW

**Comment by 1480c1** [comment]
Please use the `fixes #124` or `closes #124` format so github will auto close the issue on merge

**Comment by 1480c1** [comment]
Please use the `fixes #124` or `closes #124` format so github will auto close the issue on merge

**Comment by tianjunwork** [comment]
Thanks @xuguangxin fixing the issue. Could you update README in /ffmpeg_plugin folder? 
```
n4.3 and master:

git apply ../ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
```

**Comment by 1480c1** [comment]
@tianjunwork wrong person

**Comment by guojiansheng0925** [comment]
> Thanks @guojiansheng0925 fixing the issue. Could you update README in /ffmpeg_plugin folder?
> 
> ```
> n4.3 and master:
> 
> git apply ../ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
> ```

Done.
